CREATE TABLE CUSTOMER(
   CNAME VARCHAR(50),
   CITY VARCHAR(50)
);

INSERT INTO CUSTOMER(CNAME, CITY)
VALUES
('ANIL', 'CALCUTTA'),
('SUNIL', 'DELHI'),
('MEHUL', 'BARODA'),
('MANDAR', 'PATNA'),
('MADHURI', 'NAGPUR'),
('PRAMOD', 'NAGPUR'),
('SANDIP', 'SURAT'),
('SHIVANI', 'BOMBAY'),
('KRANTI', 'BOMBAY'),
('NAREN', 'BOMBAY');

SELECT * FROM CUSTOMER;