CREATE TABLE BRANCH(
    BNAME VARCHAR(50),
    CITY VARCHAR(50)
);

INSERT INTO BRANCH(BNAME, CITY)
VALUES
('VRCE', 'NAGPUR'),
('AJNI', 'NAGPUR'),
('KAROLABAUG', 'DELHI'),
('CHANDI', 'DELHI'),
('DHARAMPETH', 'NAGPUR'),
('M.G.ROAD', 'BENGLORE'),
('ANDHERI', 'BOMBAY'),
('VIRAN', 'BOMBAY'),
('NEHRU PLACE', 'DELHI'),
('POWAI', 'BOMBAY');

SELECT * FROM BRANCH;